services:
  catalogue:
    build:
      context: ./catalogue
    image: sudhapinisetti10/catalogue:1.0.0
    depends_on:
      - mongodb
  user:
    build : ./user
    image: sudhapinisetti10/user:1.0.0
    depends_on:
      - redis
      - mongodb
  cart:
    build:
      context: ./cart
    image: sudhapinisetti10/cart:1.0.0
    depends_on:
      - redis
      - catalogue
  shipping:
    build:
      context: ./shipping
    image: sudhapinisetti10/shipping:1.0.0
    depends_on:
      - mysql
      - cart
  payment:
    build: ./payment
    image: sudhapinisetti10/payment:1.0.0
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    build:
      context: ./frontend
    image: sudhapinisetti10/frontend:1.0.0
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
    ports:
      - "80:80"

  mongodb:
    build:
      context: ./mongodb
    image: sudhapinisetti10/mongodb:1.0.0
    volumes:
     - mongodb:/data/db

  redis:
    image: redis:7.0
    volumes:
    - redis:/data
  mysql:
    build:
      context: ./mysql
    image: sudhapinisetti10/mysql:1.0.0
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    environment: 
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  

networks:
  default:
    driver: bridge
    name: roboshop
    external: false
volumes:
  mongodb_data: # docker volume create mongodb
  redis:
  mysql:
  rabbitmq: