version: "3.8"

services:
  catalogue:
    build:
      context: ./catalogue
    image: sudhapinisetti10/catalogue:1.0.0
    depends_on:
      - mongodb

  user:
    build:
      context: ./user
    image: sudhapinisetti10/user:1.0.0
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    image: sudhapinisetti10/frontend:1.0.0
    depends_on:
      - catalogue
      - user
    ports:
      -"80:80"

  mongodb:
    build:
      context: ./mongodb
    image: sudhapinisetti10/mongodb:1.0.0

  redis:
    image: redis:7.0

networks:
  default:
    driver: bridge
    name: roboshop
    external: true