services:
  catalogue: 
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: sudhapinisetti10/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image:  sudhapinisetti10/mongodb:1.0.0
    container_name: mongodb
networks:
  default:
    driver: bridge
    name: roboshop
    external: true